MONGODB_CONNECTION_STRING = ""
TLS_CERT_PATH = ""
GAME_CATEGORIES_FILE_PATH = "/src/migrations/innitial_data/game-categories"
SUBSCRIBE_CATEGORIES_FILE_PATH = "/src/migrations/innitial_data/subscribe-categories"
BOT_TOKEN = "7375016958:AAHg8nHRVIYxyoLrYJhRtij-5iQNLj8zE3Q"